// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"url-shortener/repository/mongodb"
	"url-shortener/xsetup"
)

// Injectors from wire.go:

func InitializeSetup(ctx context.Context) (xsetup.Environment, error) {
	dapr, err := xsetup.NewDaprClient()
	if err != nil {
		return xsetup.Environment{}, err
	}
	initConfig := xsetup.NewInitConfig(ctx, dapr)
	iRedirectRepository, err := mongodb.NewMongoRepository(initConfig)
	if err != nil {
		return xsetup.Environment{}, err
	}
	environment := xsetup.NewEnvironment(dapr, initConfig, iRedirectRepository)
	return environment, nil
}
